// Shared clinical types used across Records, Nurse Station, Consultation, Wards.
// These mirror the routine clinical workflow: appointment → triage → vitals →
// consultation → treatment / admission / referral → discharge.

export type VisitStatus =
  | "booked"             // Records booked the appointment, patient not yet checked in.
  | "checked-in"         // Patient arrived at facility.
  | "awaiting-triage"    // Sitting in nurse queue.
  | "in-triage"          // Nurse is triaging.
  | "awaiting-vitals"    // Triaged, waiting for vitals to be taken.
  | "in-vitals"
  | "awaiting-consultation"
  | "in-consultation"
  | "awaiting-lab"
  | "awaiting-pharmacy"
  | "admitted"
  | "discharged"
  | "completed"
  | "cancelled";

export type TriagePriority = "emergency" | "urgent" | "semi" | "routine" | "pending";

export type VisitType = "opd" | "anc" | "lab" | "radiology" | "ward";

export type Visit = {
  id: string;                    // Internal visit id (V…)
  visitNo: string;               // Human-readable visit number (V251122001 style)
  patientId: string;
  patientName: string;
  patientSex: "M" | "F";
  patientDob: string;
  patientPhone: string;
  visitType: VisitType;
  serviceId: string;
  serviceName: string;
  department: string;
  clinicianId: string;
  clinicianName: string;
  fee: number;
  sponsor: string;               // e.g. "SELF PAY / UNINSURED - GH" or "NHIS"
  scheme: string;
  appointmentDate: string;       // YYYY-MM-DD
  appointmentTime: string;       // HH:mm
  reason: string;
  priority: TriagePriority;
  status: VisitStatus;
  /** Human label from backend {@code EncounterDto.currentStation} */
  currentStationLabel: string;
  source: "records" | "walk-in" | "internal-referral";
  createdAt: string;             // ISO timestamp
};

export type VitalsRecord = {
  id: string;
  visitId: string;
  patientId: string;
  systolic: string;
  diastolic: string;
  temperature: string;
  pulse: string;
  spo2: string;
  weight: string;
  height: string;
  respiratoryRate: string;
  bmi: string;
  notes: string;
  recordedBy: string;
  recordedAt: string;
};

export type ConsultationNote = {
  id: string;
  visitId: string;
  patientId: string;
  chiefComplaint: string;
  historyOfPresentingComplaint: string;
  examinationFindings: string;
  assessment: string;
  plan: string;
  authoredBy: string;
  authoredRole: "nurse" | "doctor" | "midwife";
  authoredAt: string;
};

export type TreatmentEntry = {
  id: string;
  visitId: string;
  patientId: string;
  drug: string;
  dose: string;
  route: string;
  frequency: string;
  durationDays: number;
  instructions: string;
  prescribedBy: string;
  prescribedAt: string;
  status: "ordered" | "administered" | "withheld" | "cancelled";
};

export type Admission = {
  id: string;
  patientId: string;
  visitId: string;
  ward: string;
  bed: string;
  reason: string;
  admittedBy: string;
  admittedAt: string;
  dischargedAt?: string;
  dischargeSummary?: string;
};

export type Referral = {
  id: string;
  visitId: string;
  patientId: string;
  fromDepartment: string;
  toDepartment: string;
  reason: string;
  urgency: "routine" | "urgent" | "stat";
  referredBy: string;
  referredAt: string;
  status: "pending" | "accepted" | "completed";
};

export type MedicalAlert = {
  id: string;
  patientId: string;
  category: "allergy" | "chronic" | "infectious" | "implant" | "general";
  label: string;
  notes: string;
  recordedBy: string;
  recordedAt: string;
};

// ── Orders generated by clinicians (doctors/nurses) and fulfilled by other roles ──

export type OrderUrgency = "routine" | "urgent" | "stat";

export type LabOrderStatus =
  | "ordered"           // Doctor placed order, awaiting payment / sample
  | "awaiting-payment"
  | "awaiting-sample"
  | "in-progress"       // Lab is processing
  | "completed"         // Result authorised
  | "cancelled";

export type LabResultRow = {
  analyte: string;
  refRange: string;
  unit: string;
  value: string;
  flag: "normal" | "high" | "low" | "critical";
};

export type LabOrder = {
  id: string;
  visitId: string;
  patientId: string;
  patientName: string;
  patientSex: "M" | "F";
  patientDob: string;
  testCode: string;
  testName: string;
  category: string;       // Haematology, Chemistry, Microbiology, …
  clinicalNotes: string;  // The doctor's clinical question
  urgency: OrderUrgency;
  orderedBy: string;
  orderedAt: string;
  status: LabOrderStatus;
  results?: LabResultRow[];
  resultEnteredBy?: string;
  resultEnteredAt?: string;
  resultSummary?: string;
  fee: number;
};

export type PrescriptionStatus =
  | "ordered"
  | "awaiting-payment"
  | "ready-to-dispense"
  | "partially-dispensed"
  | "dispensed"
  | "cancelled";

export type PrescriptionLine = {
  id: string;
  drug: string;
  strength: string;
  form: string;            // tablet, capsule, syrup, IV
  route: string;
  frequency: string;
  durationDays: number;
  quantity: number;
  instructions: string;
  fee: number;
  dispensedQty?: number;
  dispensedAt?: string;
  dispensedBy?: string;
};

export type Prescription = {
  id: string;
  visitId: string;
  patientId: string;
  patientName: string;
  patientSex: "M" | "F";
  patientDob: string;
  prescribedBy: string;
  prescribedAt: string;
  status: PrescriptionStatus;
  lines: PrescriptionLine[];
  pharmacyNotes?: string;
};

export type RadiologyOrderStatus =
  | "ordered"
  | "awaiting-payment"
  | "scheduled"
  | "in-progress"
  | "reported"
  | "cancelled";

export type RadiologyOrder = {
  id: string;
  visitId: string;
  patientId: string;
  patientName: string;
  patientSex: "M" | "F";
  patientDob: string;
  modality: string;        // X-Ray, CT, US, MRI
  studyName: string;
  clinicalNotes: string;
  urgency: OrderUrgency;
  orderedBy: string;
  orderedAt: string;
  status: RadiologyOrderStatus;
  reportText?: string;
  reportedBy?: string;
  reportedAt?: string;
  fee: number;
};

// ── Billing ──────────────────────────────────────────────────────────────
// Each clinical event that has a price generates a billing line item. The
// item travels with the visit and is settled by the billing/cashier officer.

export type BillingItemKind =
  | "consultation"
  | "lab"
  | "radiology"
  | "pharmacy"
  | "procedure"
  | "ward"
  | "other";

export type BillingItemStatus = "pending" | "paid" | "claimed" | "waived" | "cancelled";

export type BillingLineItem = {
  id: string;
  visitId: string;
  patientId: string;
  kind: BillingItemKind;
  description: string;
  quantity: number;
  unitPrice: number;
  amount: number;
  sponsor: string;                  // SELF PAY, NHIS, …
  serviced: boolean;                // True once the service has been delivered
  servicedAt?: string;
  status: BillingItemStatus;
  paidAt?: string;
  paymentMethod?: string;
  receiptNo?: string;
  sourceRef?: string;               // FK back to lab order / prescription / etc.
  createdBy: string;
  createdAt: string;
};
